ARG ARG_BASE_IMAGE
FROM $ARG_BASE_IMAGE

ENV M_MODULE_SHORT=azepi
ENV M_CONFIG_NAME=azepi-config.yml
ENV M_STATE_FILE_NAME=state.yml

ENV M_TEMPLATES=/usr/local/epicli/data/common/defaults
ENV M_WORKDIR=/workdir
ENV M_RESOURCES=/resources
ENV M_SHARED=/shared

USER root

COPY $M_RESOURCES/ $M_RESOURCES/
COPY $M_WORKDIR/ $M_WORKDIR/

ARG ARG_HOST_UID=1000
ARG ARG_HOST_GID=1000

RUN chown -R $ARG_HOST_UID:$ARG_HOST_GID \
    $M_WORKDIR/ \
    $M_RESOURCES/

USER $ARG_HOST_UID:$ARG_HOST_GID

ENV PYTHONPATH=$M_RESOURCES:$PYTHONPATH

WORKDIR $M_WORKDIR/

ARG ARG_M_VERSION="unknown"
ENV M_VERSION=$ARG_M_VERSION

ENTRYPOINT ["/usr/local/bin/python3", "./entrypoint.py"]
